### ISSUE TITLE
amco codes opnemen

### ISSUE THREAD

**Issue by phpetra** [histograph/data#1]
[ ] zijn die rechtenvrij?
[ ] hebben we een recente versie?
[ ] moet die nog gemapped?

**Comment by mmmenno** [comment]
Probleem: Amco's identificeren meerdere gemeentes, dus ik weet niet hoe je ze erin krijgt. Niet met een sameHgConcept relatie iig.

We moeten besluiten of we ons datamodel zo aanpassen dat ook concepten die meerdere concepten beschrijven er een plaats in krijgen.

Simpele oplossing: opnemen in 'data' property.

**Comment by mmmenno** [comment]
Ze zitten nu in de data property

**Comment by bertspaan** [comment]
Nieuwe taak voor Bert: `data`-velden doorzoekbaar maken!
