### ISSUE TITLE
GG: waar zijn alle volgende geometrieën gebleven? Zie alleen 1812!

### ISSUE THREAD

**Issue by mmmenno** [histograph/data#14]
Vgl Amsterdam. In de pits.ndjson staan geometrieën van 1812, 1841, 1871, etc. opgenomen, maar ik zie alleen die van 1812 terug.

Gaat 't mis omdat ze dezelfde source-uri hebben?

**Comment by bertspaan** [comment]
Ja, dat mag niet meer, omdat dat van alles en nog wat nodeloos ingewikkeld maakt... Ik ben zeker ontvankelijk voor omkoping en goede argumenten om 't tóch weer in te voeren etc., maar volgens mij kan 't eenvoudiger: een soort spook-PIT, voor elke gemeente met een URI in Gemeentegeschiedenis: deze PIT heeft een URI en een `sameHgConcept`-relatie met alle PIT's die deze URI hebben. (Wellicht is dit niet zo eenvoudig voor jullie te implementeren in de PIT Importer...)

**Comment by mmmenno** [comment]
So the same source-uri for different pits is not allowed? Why not? It's different geometries of the same thing. And on the source uri you'll find all these geometries!

**Comment by mmmenno** [comment]
O, jij zit ook na het eten te typen ;-)

**Comment by mmmenno** [comment]
Het nadeel van spookpits is dat het conceptueel wat scheef zit: heb je allemaal nette places in time, gooi je er weer een place in all times tegenaan.

Het voordeel is wel weer dat je eventuele begin- en einddatum van een gemeente dan onafhankelijk van de geometrie goed kan aangeven. En dat je ook gemeentes kunt importeren waar we (nog) geen geometrie van hebben.

In de PiT Importer is _alles_ eenvoudig te implementeren ;-) Denk wel dat het logisch is als we twee datasets maken: gemeentegeschiedenis en gemeentegeschiedenis-geometries ofzo. Ik zal eens wat proberen.

**Comment by bertspaan** [comment]
Laten we 't even kort bespreken (deze week nog?). Momenteel is 't feit dat er meerdere PIT's kunnen bestaan met dezelfde URI de bron van een hoop ellende in Core - 't wordt er erg complex en langzaam van. Dat is zeker geen reden om 't niet toe te staan, maar was wel nu even een makkelijke oplossing voor paar bugs... @wires en ik herschrijven binnenkort een groot stuk van Core (op [Terschelling](http://histograph.io/viewer/#search=terschelling) of een ander eiland :palm_tree: ), dan komt ook dit opnieuw aan bod.

**Comment by mmmenno** [comment]
Ik ben de zgn spookpits al aan het maken. Zie genoemde voordelen.

**Comment by bertspaan** [comment]
Mooi. Dan ga ik nu eten.

**Comment by mmmenno** [comment]
zoiets dus: http://geothesaurus.nl/hgconcept/geonames/2755374

**Comment by ghost** [comment]
heel cool.

**Comment by phpetra** [comment]
Ziet er idd wel koel uit!
Kan alleen even niet alle consequenties overzien...wat betekent dit voor bv de timelapse in de viewer?
Of de atlas verstedelijking? Hoe zit die in elkaar?

-------- Original Message --------

**Comment by ghost** [comment]
by the way @mmmenno, heb je de gemeentegeschiedenis-geometries geimporteerd van de oorspronkelijke shapefiles (een voor elk jaar), of eerst PiTs gemaakt zoals op gemeentegeschiedenis.nl uit postgis wordt gehaald?

ben namelijk aan het nadenken hoe/wat we moeten doen om datasets in het algemeen klaar te maken voor import. Cshapes had eigenlijk al PiTs met begin- en einddatum, maar Geacron heeft net als de NLGis shapefiles 1 laag per jaar.

**Comment by mmmenno** [comment]
@hpfast Ik heb ze van de gemeentegeschiedenis api, dus ik krijg alleen maar van jaren waarin ze gewijzigd zijn. Het eindjaar heb ik er steeds zelf bij uitgerekend, of op null gezet indien nog steeds geldig.
