### ISSUE TITLE
GG: absorbed, originated etc also in geometry-less pits

### ISSUE THREAD

**Issue by mmmenno** [histograph/data#15]

**Comment by mmmenno** [comment]
All relations have been added. Wrote a new script to get all info from gg (see https://github.com/erfgoed-en-locatie/historische-geocoder/tree/gh-pages/data/gemeentegeschiedenis ), found and solved some errors in gg itself in the process.

**Comment by bertspaan** [comment]
And it works:

![image](https://cloud.githubusercontent.com/assets/1194896/7840400/7a4fc3f4-0497-11e5-8336-77636a7be9d1.png)

**Comment by bertspaan** [comment]
![image](https://cloud.githubusercontent.com/assets/1194896/7840507/f7608798-0497-11e5-801d-36eafe51ac80.png)

**Comment by bertspaan** [comment]
@mmmenno: this is fun!

**Comment by mmmenno** [comment]
@bertspaan Cool! I want that! Is it difficult to let the api spit out other relations than just the sameHgConcepts?

**Comment by bertspaan** [comment]
No. This should be very easy. But it's something that I'd like to design well, I do not want to hack it in in an hour.

**Comment by mmmenno** [comment]
Ok. It's just that it's probably fun as well to browse through the geothesaurus, following all these relations.

**Comment by bertspaan** [comment]
Yes. I'll have a look at Rutger's code tomorrow, and see whether it's easy to add it. Otherwise, I'll do it during the rewrite of some Core parts (:palm_tree:...).

**Comment by mmmenno** [comment]
Super! I'll be there tomorrow to remind you ;-)

**Comment by bertspaan** [comment]
:expressionless:
