### ISSUE TITLE
Nalopen welke datasets nu wel de juiste sws.geonames hebben en welke niet

### ISSUE THREAD

**Issue by phpetra** [histograph/data#16]
- [x] pleiades
- [x] ilvb
- [x] poorterboeken
- [x] atlas-verstedelijking
- [x] graafschappen
- [x] simon-hart
- [x] verdwenen-dorpen
- [x] voc-opvarenden
- [x] carnaval
- [x] departmenten1812

... andere?

**Comment by bertspaan** [comment]
We kunnen misschien morgen ook een begin maken met 't overzetten van deze datasets naar de nieuwe repo's.

**Comment by bertspaan** [comment]
Dit zijn nu op dit moment supreme alle datasets in `erfgoed-en-locatie/historische-geocoder` die NDJSON-bestanden met verkeerde GeoNames-URI's bevatten:

![image](https://cloud.githubusercontent.com/assets/1194896/7856913/e85ee47a-052c-11e5-9b9a-69a2a4425516.png)

En in al déze directory's komen verkeerde GeoNames-URI's voor, ook in andere bestanden dan NDJSON:

![image](https://cloud.githubusercontent.com/assets/1194896/7856946/2ce17306-052d-11e5-8e0f-c0dee3a75b47.png)

**Comment by bertspaan** [comment]
Klaar. Bovendien accepteert nieuwe Core www-URI's, naast sws.
