### ISSUE TITLE
example of config for data source?

### ISSUE THREAD

**Issue by ghost** [histograph/data#18]
I've successfully installed histograph core and am trying to run data import scripts but get the error:

```
$node index.js geonames

/home/dev/build/data/geonames/geonames.js:49
    var countryFilenames = config.countries.map(function(country) {
                                           ^
    TypeError: Cannot read property 'countries' of undefined
```

. README says to configure data sources in histograph configuration file. Do I follow correctly that geonames importer is [expecting](https://github.com/histograph/data/blob/master/geonames/geonames.js#L49) a countries mapping in the histograph configuration file? If so, can someone give an example of such a config?

**Comment by wires** [comment]
This tool still has some rough edges, but you deduced correctly that the config file is not up to date.

I created an issue, @bertspaan should be able to help us https://github.com/histograph/config/issues/1

**Comment by ghost** [comment]
ok thanks @wires! closing this one then.

**Comment by wires** [comment]
Reopening, I think this is still a valid issue, `data` tool needs to be more resilient to faulty user input and/or do better error reporting

**Comment by ghost** [comment]
ok, true, and going further on that I would suggest documentation of what that config property should look like might belong here rather than in the [config](https://github.com/histograph/config) repo.

**Comment by wires** [comment]
Agreed the config system can use some work, this is on the radar. However, config will remain shared between the different components... we need better documentation of config options though and refer to it at the right places

**Comment by bertspaan** [comment]
Yes, I did not check in the latest version of my configuration file. I'll do that once I have a new hard drive and access to my old drive's files :expressionless:

**Comment by bertspaan** [comment]
Done. See https://github.com/histograph/config/issues/1
