### ISSUE TITLE
kloeke codes opnemen

### ISSUE THREAD

**Issue by phpetra** [histograph/data#2]
[ ] relevante user story voor kloeke codes?
[ ] hebben we de meest actuele set?
[ ] rechten?

**Comment by mmmenno** [comment]
Ik zal hier achter aan gaan. De kloeke codes heb ik, en ze zijn, waar mogelijk, ook al gemapt naar geonames. Licentie zal ik ze vragen.

**Comment by mmmenno** [comment]
Ik zie trouwens dat ik alleen de nederlandse plaatsen gemapt heb naar geonames. En er zijn heel veel kloeke plaatsen in België en zelfs Frankrijk (nl taalgebied), dus die zouden eerst nog ge-aligned moeten. Iets meer voeten in aarde dus.

**Comment by phpetra** [comment]
Nu zit heel kloeke erin maar zijn alleen relaties gelegd met de Nederlandse plaatsen.
De rest blijft een open puntje...

**Comment by mmmenno** [comment]
Ik close 'm voor nu, want we hebben sowieso nog geen buitenlandse plaatsen om aan te relateren

**Comment by phpetra** [comment]
Maar daarom heb ik 'm juist open gelaten.... het is nog niet opgelost en ook is niet duidelijk wat we er wel of niet mee gaan doen?

Zelfde geldt trouwens voor issue #8 , het zijn ook reminders om dit nog eens te bespreken.

**Comment by bertspaan** [comment]
Welke buitenlanden willen we? Ik kan met nieuwe TGN- & GeoNames-importers heel eenvoudig buitenlanden (of stukken daarvan, bv. slechts een paar provincies) importeren.
