### ISSUE TITLE
Buitenlandse plaatsen uit Simon Hart

### ISSUE THREAD

**Issue by phpetra** [histograph/data#3]
In ieder geval de Deense (en Duitse?) die al gemapped zijn naar geonames

[ ] moeite insteken om andere buitenlandse plaatsen te mappen?

**Comment by jobspierings** [comment]
@bertspaan zegt nu weer dit: 

> "GeoNames importer can currently imports data per country, and places/URIs from a user-provided list of GeoNames URLs - Danish and German places can be added to this list! :de: :beer: "
