### ISSUE TITLE
Missing dependency 'adm-zip' on executing node index.js nwb

### ISSUE THREAD

**Issue by reinvantveer** [histograph/data#31]
reinv@lingui:~/data/Github/histograph/data$ node index.js nwb
module.js:328
    throw err;
    ^

Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/data/Github/histograph/data/nwb/nwb.js:6:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
reinv@lingui:~/data/Github/histograph/data$ npm install adm-zip
histograph-data@1.0.0 /var/data/Github/histograph/data
└── adm-zip@0.4.7  extraneous

npm WARN EPACKAGEJSON histograph-data@1.0.0 No repository field.
reinv@lingui:~/data/Github/histograph/data$ node index.js nwb
Processing dataset nwb:
  Executing step download...
    Done!
  Executing step convert...
    Done!
  Executing step done...
    Done!

All datasets done!
    Done!

All datasets done!

**Comment by bertspaan** [comment]
Rein! Je moet nieuwe branch `data-modules` gebruiken!

**Comment by reinvantveer** [comment]
Ow! Goed dat ik het weet!

:)

Op ma 11 jan. 2016 13:54 schreef Bert Spaan notifications@github.com:

**Comment by bertspaan** [comment]
Maaaar! Ik heb alleen nog maar de modules voor GeoNames en TGN naar nieuwe structuur geconverteerd. Maar 't is niet moeilijk om dat ook voor BAG en NWB te doen. Misschien kun jij dat doen? (Hier in NYC zijn BAG en NWB beetje zinloos, NAMELIJK.)

**Comment by reinvantveer** [comment]
Lijkt me een mooi klusje voor maandag a.s, mijn Histograph dag. En overigen.

Op ma 11 jan. 2016 18:01 schreef Bert Spaan notifications@github.com:

**Comment by bertspaan** [comment]
Ok, zie https://github.com/histograph/data-geonames en https://github.com/histograph/data-tgn hoe je dat doet - en ik help je graag!

**Comment by sbocconi** [comment]
I assume this issue is closed, if there is still something after trying the conversion for BAG and NWB better open a more specific issue.

**Comment by sbocconi** [comment]
Hi @reinvantveer, I have opened a specific issue for the creation of the BAG and NWB data sets, it is here: https://github.com/histograph/data/issues/29
Are you maybe working at this? I am also having a look

**Comment by reinvantveer** [comment]
Yes I'm doing BAG at the moment. Got as far as neatly recursively unpacking
those dreadful zips (at least the Amstelveen test set) , so I can get set
to streaming thise dreadful XMLs to ndjson :)

Greetings,
Rein

Op wo 20 jan. 2016 10:35 schreef Stefano Bocconi notifications@github.com:
