### ISSUE TITLE
DBpedia opnemen en alignen

### ISSUE THREAD

**Issue by phpetra** [histograph/data#5]
- de vorige versie van DBpedia was nergens aan gemapped en zorgde daarvoor voor dubbele PiTs. Dus een nieuwe import heeft alleen zin als de set gemapped wordt naar geonames of een andere bestaande source.

[ ] uitzoeken wat er in oorspronkelijke set zit (alleen NL?)
[ ] mappen naar andere source, en eventueel aanvullen?

**Comment by mmmenno** [comment]
Omdat we voor plaatsen en gemeentes al andere goede referentiebronnen hebben zou ik dbpedia geen hoge prioriteit geven. Alleen voor gewesten, departementen etc zou dpbedia op kortere termijn nuttig zijn, wat mij betreft.
