### ISSUE TITLE
gemeentegeschiedenis uitbreiden met data na 2007

### ISSUE THREAD

**Issue by phpetra** [histograph/data#6]
(PDOK) Kadaster heeft nu shapefiles van 2013, 2014 en 2015 gepubliceerd, met shapefiles zie:
https://www.pdok.nl/nl/producten/pdok-downloads/basis-registratie-kadaster/bestuurlijke-grenzen-historie

Is het de moeite waard om de wijzigingen sinds 2007 ook te gaan verwerken???
Lijkt wellicht de moeite waard... ?

**Comment by mmmenno** [comment]
Importeren van pdok-bestuurlijke-grenzen dataset lijkt me nuttig. Het werk zal 'm zitten in het koppelen van de gemeentes met die van gemeentegeschiedenis. Alhoewel, in de pdok data zijn cbs-codes opgenomen, zie ik net, dus dat zal wel te overzien zijn.

**Comment by mmmenno** [comment]
Ik zou 'm dus als aparte dataset doen, met sameHgConcept relaties naar gemeentegeschiedenis uri's, als dat niet al duidelijk was
