### ISSUE TITLE
Nienes set van departementen voorzien van uri's

### ISSUE THREAD

**Issue by phpetra** [histograph/data#8]
Ze hebben nu alleen namen, geen uri's omdat er nog geen source is die ze heeft.

Optie 1:
Op wikipedia zijn ze terug te vinden dus wellicht dat DBpedia ze inderdaad heeft?
Zie: https://nl.wikipedia.org/wiki/Departementen_in_de_Nederlanden
- [ ] uitzoeken of ze daar gevonden kunnen worden

Optie 2:
Gemeentegeschiedenis uri's voor departementen gaan gebruiken?
http://www.gemeentegeschiedenis.nl/departement/NM
- [ ] Is dat handig? Hoe persistent zijn die?

**Comment by phpetra** [comment]
Set staat nu nog hier: https://github.com/erfgoed-en-locatie/historische-geocoder/tree/gh-pages/data/Departementen

Later verhuizen naar histograph-data

**Comment by phpetra** [comment]
Er is gekozen voor optie 2. En deze zijn nu opgenomen in deze set. 
In de gemeentegeschiednis set zitten de departementen op dit moment nog niet en het toevoegen ervan gaat vandaag mis.

Later nakijken of deze relaties wel goed gelegd worden en of de relaties kloppen.

**Comment by mmmenno** [comment]
Ik vermoed dat alles al in kannen en kruiken is, maar dat weten we pas echt zeker op het moment dat de api liesIn relaties door gaat geven.

De dataset departementen1812 heeft een bron-uri waar gemeentes een liesIn relatie naar leggen. Dat de  dataset departementen1812 heet en de bron-uri een http://www.gemeentegeschiedenis.nl/etc is lijkt misschien wat raar, maar volgens mij kunnen verschillende datasets best als bron-uri iets binnen hetzelfde domein hebben (handle!).

**Comment by mmmenno** [comment]
Omdat de departementen al voorzien zijn van uri's close ik 'm maar
