### ISSUE TITLE
Nienes set van provincies inlezen

### ISSUE THREAD

**Issue by phpetra** [histograph/data#9]

**Comment by phpetra** [comment]
Zie hier: https://github.com/erfgoed-en-locatie/historische-geocoder/tree/gh-pages/data/Bestuurlijke_Grenzen

De geojson files zijn de uiteindelijk te gebruiken bestanden.

**Comment by mmmenno** [comment]
Ziet er goed uit. Alleen de property hgIn zal iets mis zijn gegaan: Almere ligt in Ethiopië. Maar goed, die hebben we ook niet nodig - de gg uri's en geonames uri's moeten genoeg zijn!

**Comment by phpetra** [comment]
Done.
